/**
 * Created by romain on 21/04/2017.
 */

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

export const GET_ALL_ROOMS_SUCCESS = 'LOAD_ROOMS_SUCCESS';
export const GET_ALL_ROOMS_UNSUCCESS = 'LOAD_ROOMS_UNSUCCESS';

export const CHANGE_CURRENT_DATE = 'CHANGE_CURRENT_DATE';

export const GET_ALL_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const GET_ALL_LESSONS_UNSUCCESS = 'LOAD_LESSONS_UNSUCCESS';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';
export const ADD_LESSON_UNSUCCESS = 'ADD_LESSON_UNSUCCESS';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';
export const UPDATE_LESSON_UNSUCCESS = 'UPDATE_LESSON_UNSUCCESS';

export const GET_ALL_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const GET_ALL_STUDENTS_UNSUCCESS = 'LOAD_STUDENTS_UNSUCCESS';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_UNSUCCESS = 'ADD_STUDENT_UNSUCCESS';

export const GET_ALL_TEACHERS_SUCCESS = 'LOAD_TEACHERS_SUCCESS';
export const GET_ALL_TEACHERS_UNSUCCESS = 'LOAD_TEACHERS_UNSUCCESS';
export const ADD_TEACHER_SUCCESS = 'ADD_TEACHER_SUCCESS';
export const ADD_TEACHER_UNSUCCESS = 'ADD_TEACHER_UNSUCCESS';

export const GET_ALL_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const GET_ALL_COURSES_UNSUCCESS = 'LOAD_COURSES_UNSUCCESS';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_UNSUCCESS = 'ADD_COURSE_UNSUCCESS';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
export const DELETE_LESSON_UNSUCCESS = 'DELETE_LESSON_UNSUCCESS';

export const SET_AUTH = 'SET_AUTH_BASE64';
export const UNSET_AUTH = 'UNSET_AUTH_BASE64';
export const UPDATE_AUTH = 'UPDATE_AUTH_ACTION';